name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!!"
  echo_sayonara_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sayonara!!"
  multiple_steps:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sayonara!!"
      - run: echo "arigato!!"
      - run: echo "gomennasai!!"
      - run: echo "hajimemashite!!"
      - run: echo "dotirasamadesuka!!"
